application: genwisproject
version: 20180130t061833
runtime: php55
api_version: 1
threadsafe: yes

handlers:

- url: /(.*\.(gif|png|jpg|ico|bmp|css|otf|eot|svg|ttf|woff|js))
  static_files: \1
  upload: (.*\.(gif|png|jpg|ico|bmp|css|otf|eot|svg|ttf|woff|js))

- url: /login
  script: login.php

- url: /register
  script: register.php

- url: /(.+\.php)$
  script: \1
  
- url: /
  script: index.php